# Generated by Django 4.0.2 on 2022-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
