# Generated by Django 3.2.7 on 2021-11-18 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_links_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
