# Generated by Django 3.2.9 on 2021-11-19 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_links_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='original',
            field=models.TextField(validators=[django.core.validators.URLValidator]),
        ),
    ]
