# Generated by Django 3.2.9 on 2021-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_links_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='original',
            field=models.TextField(),
        ),
    ]
